version: '3'

services:
  client:
    build:
      context: ./
    ports:
      - 80:80
    environment:
      - REACT_APP_SAME_ORIGIN_SOCKET_PORT=5005

  server:
    build:
      context: ./server
    ports:
      - '5005:5005'
    environment:
      - PORT=5005
      - ALLOW_ORIGIN="http://localhost"
